server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
      
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      itemCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000 # 2 seconds
        response-timeout: 3s  # wait 3 seconds max per response
      default-filters:
        - AddResponseHeader=X-Gateway-Header, REAL-FREEE-GW
      routes:

        # Route: Item Service
        - id: item-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/items/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: GET, POST
            - name: CircuitBreaker
              args:
                name: itemCB
                fallbackUri: forward:/fallback/item
            - RewritePath=/api/items/(?<segment>.*), /${segment}

        # Route: Media Service
        - id: media-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/media/**
          filters:
            - RewritePath=/api/media/(?<segment>.*), /${segment}

        # Route: Auth Service
        - id: auth-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /${segment}