spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 3s
      default-filters:
        - AddResponseHeader=X-Gateway-Header, REAL-FREEE-GW
      # routes:
      #   - id: item-service
      #     uri: http://localhost:8081
      #     predicates:
      #       - Path=/item-service/api/**
      #     filters:
      #       - RewritePath=/item-service/api/(?<remaining>.*), /api/${remaining}
      #     order: 1
      routes:
        - id: item-service
          uri: http://localhost:8081
          predicates:
            - Path=/item-service/api/**
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY, GATEWAY_TIMEOUT
                methods: GET, POST
            - name: CircuitBreaker
              args:
                name: itemCB
                fallbackUri: forward:/fallback/item
            - RewritePath=/item-service/api/(?<remaining>.*), /api/${remaining}
            # - name: RequestRateLimiter
            #   args:
            #     redis-rate-limiter:
            #       replenishRate: 10  # 10 requests per second
            #       burstCapacity: 20   # Allows 20 requests in burst
            #       requestedTokens: 1  # 1 token per request
          order: 1

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      itemCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
cors:
  allowed-origins:
    - http://localhost:5173
    - https://real-freee.com